const questionStore = [
  // easy difficulty questions
  {
    question: "What is the speed of light",
    subject: "Physics",
    topic: "Waves",
    difficulty: "easy",
    marks: 5,
  },
  {
    question: "How does photosynthesis work",
    subject: "Biology",
    topic: "Plant Biology",
    difficulty: "easy",
    marks: 5,
  },
  {
    question: "Define Newton's First Law of Motion",
    subject: "Physics",
    topic: "Mechanics",
    difficulty: "easy",
    marks: 5,
  },
  {
    question: "What is the capital of France",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "easy",
    marks: 5,
  },
  {
    question: "Solve for x: 2x + 5 = 15",
    subject: "Mathematics",
    topic: "Algebra",
    difficulty: "easy",
    marks: 5,
  },
  {
    question: "List the planets in our solar system",
    subject: "Astronomy",
    topic: "Solar System",
    difficulty: "easy",
    marks: 5,
  },
  {
    question: "Who wrote Romeo and Juliet",
    subject: "Literature",
    topic: "Shakespeare",
    difficulty: "easy",
    marks: 5,
  },
  {
    question: "What is the chemical symbol for gold",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "easy",
    marks: 5,
  },
  {
    question: "Simplify the expression: 3(2x - 5)",
    subject: "Mathematics",
    topic: "Algebra",
    difficulty: "easy",
    marks: 5,
  },
  {
    question: "Name three types of clouds",
    subject: "Meteorology",
    topic: "Weather",
    difficulty: "easy",
    marks: 5,
  },
  {
    question: "Who is known as the 'Father of Computer Science'",
    subject: "Computer Science",
    topic: "History",
    difficulty: "easy",
    marks: 5,
  },
  {
    question: "What is the powerhouse of the cell",
    subject: "Biology",
    topic: "Cell Biology",
    difficulty: "easy",
    marks: 5,
  },
  {
    question: "Solve the equation: 4x - 7 = 5",
    subject: "Mathematics",
    topic: "Algebra",
    difficulty: "easy",
    marks: 5,
  },
  {
    question: "In which year did World War I begin",
    subject: "History",
    topic: "World War I",
    difficulty: "easy",
    marks: 5,
  },
  {
    question: "What is the largest mammal on Earth",
    subject: "Biology",
    topic: "Marine Biology",
    difficulty: "easy",
    marks: 5,
  },

  // medium difficulty questions
  {
    question: "Explain the concept of natural selection",
    subject: "Biology",
    topic: "Evolution",
    difficulty: "medium",
    marks: 10,
  },
  {
    question: "Solve the quadratic equation: x^2 - 4x + 4 = 0",
    subject: "Mathematics",
    topic: "Quadratic Equations",
    difficulty: "medium",
    marks: 10,
  },
  {
    question: "What is the theory of relativity",
    subject: "Physics",
    topic: "Relativity",
    difficulty: "medium",
    marks: 10,
  },
  {
    question: "Name three elements in the periodic table",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "medium",
    marks: 10,
  },
  {
    question: "Who won the Nobel Prize in Literature in 2020",
    subject: "Literature",
    topic: "Nobel Prize",
    difficulty: "medium",
    marks: 10,
  },
  {
    question: "What is the capital of Japan",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "medium",
    marks: 10,
  },
  {
    question: "Solve the system of equations: 2x + y = 10, x - y = 2",
    subject: "Mathematics",
    topic: "Algebra",
    difficulty: "medium",
    marks: 10,
  },
  {
    question: "Define the term 'Photosynthesis'",
    subject: "Biology",
    topic: "Plant Biology",
    difficulty: "medium",
    marks: 10,
  },
  {
    question: "Who discovered penicillin",
    subject: "Medicine",
    topic: "Medical History",
    difficulty: "medium",
    marks: 10,
  },
  {
    question: "What is the boiling point of water in Celsius",
    subject: "Chemistry",
    topic: "Physical Chemistry",
    difficulty: "medium",
    marks: 10,
  },
  {
    question: "Name the largest desert in the world",
    subject: "Geography",
    topic: "Deserts",
    difficulty: "medium",
    marks: 10,
  },
  {
    question: "Solve the equation: 3x + 7 = 16",
    subject: "Mathematics",
    topic: "Algebra",
    difficulty: "medium",
    marks: 10,
  },
  {
    question: "In which year did the Titanic sink",
    subject: "History",
    topic: "Titanic",
    difficulty: "medium",
    marks: 10,
  },
  {
    question: "What is the speed of sound in air",
    subject: "Physics",
    topic: "Acoustics",
    difficulty: "medium",
    marks: 10,
  },
  {
    question: "Name the process by which plants make their own food",
    subject: "Biology",
    topic: "Plant Biology",
    difficulty: "medium",
    marks: 10,
  },

  // hard difficulty questions
  {
    question: "Explain the concept of quantum entanglement",
    subject: "Physics",
    topic: "Quantum Physics",
    difficulty: "hard",
    marks: 15,
  },
  {
    question: "What is the Riemann Hypothesis",
    subject: "Mathematics",
    topic: "Number Theory",
    difficulty: "hard",
    marks: 15,
  },
  {
    question: "Describe the process of cellular respiration",
    subject: "Biology",
    topic: "Cell Biology",
    difficulty: "hard",
    marks: 15,
  },
  {
    question: "Who proposed the uncertainty principle",
    subject: "Physics",
    topic: "Quantum Mechanics",
    difficulty: "hard",
    marks: 15,
  },
  {
    question: "Explain the concept of entropy",
    subject: "Physics",
    topic: "Thermodynamics",
    difficulty: "hard",
    marks: 15,
  },
  {
    question: "What is the molecular structure of DNA",
    subject: "Biology",
    topic: "Genetics",
    difficulty: "hard",
    marks: 15,
  },
  {
    question: "Solve the system of equations: 3x - 2y = 5, 2x + y = 8",
    subject: "Mathematics",
    topic: "Algebra",
    difficulty: "hard",
    marks: 15,
  },
  {
    question: "Name three subatomic particles",
    subject: "Physics",
    topic: "Particle Physics",
    difficulty: "hard",
    marks: 15,
  },
  {
    question: "Who wrote 'The Origin of Species'",
    subject: "Biology",
    topic: "Evolution",
    difficulty: "hard",
    marks: 15,
  },
  {
    question: "Define the term 'Molecular Biology'",
    subject: "Biology",
    topic: "Molecular Biology",
    difficulty: "hard",
    marks: 15,
  },
  {
    question: "What is the pH of a neutral solution",
    subject: "Chemistry",
    topic: "Acids and Bases",
    difficulty: "hard",
    marks: 15,
  },
  {
    question: "Name the largest ocean on Earth",
    subject: "Geography",
    topic: "Oceans",
    difficulty: "hard",
    marks: 15,
  },
  {
    question: "Solve the differential equation: dy/dx = x^2",
    subject: "Mathematics",
    topic: "Differential Equations",
    difficulty: "hard",
    marks: 15,
  },
  {
    question: "Who discovered the electron",
    subject: "Physics",
    topic: "Atomic Physics",
    difficulty: "hard",
    marks: 15,
  },
  {
    question: "Explain the process of protein synthesis",
    subject: "Biology",
    topic: "Genetics",
    difficulty: "hard",
    marks: 15,
  },
];

module.exports = questionStore;
